export const categoryColors: { [key: string]: string } = {
  Groceries: "#FFD700",
  Rent: "#FF6347",
  Salary: "#32CD32",
  Freelancing: "#6495ED",
  Utilities: "#00CED1",
  Electronics: "#8A2BE2",
  "Dining Out": "#FFA07A",
  "Breakfast Supplies": "#FFDEAD",
  "Household Items": "#F0E68C",
  "Christmas Gifts": "#FF69B4",
  "New Year Party Supplies": "#DB7093",
  "Thanksgiving Groceries": "#CD853F",
  Bonus: "#6B8E23",
  "Consulting Work": "#4682B4",
  "Part-time Job": "#DAA520",
  "Online Sales": "#20B2AA",
  "Freelance Writing": "#778899",
  "End of Year Bonus": "#5F9EA0",
  "Thanksgiving Freelance": "#BDB76B",
  Default: "#D3D3D3",
};

export const categoryEmojies: { [key: string]: string } = {
  Groceries: "🛒",
  Rent: "🏠",
  Salary: "💰",
  Freelancing: "👨🏻‍💻",
  Utilities: "💡",
  Electronics: "🖥️",
  "Dining Out": "🍽️",
  "Breakfast Supplies": "🥐",
  "Household Items": "🏡",
  "Christmas Gifts": "🎁",
  "New Year Party Supplies": "🎉",
  "Thanksgiving Groceries": "🦃",
  Bonus: "🎊",
  "Consulting Work": "💼",
  "Part-time Job": "⌚",
  "Online Sales": "🛒",
  "Freelance Writing": "✍️",
  "End of Year Bonus": "🍾",
  "Thanksgiving Freelance": "🍂",
  Default: "🫰🏼",
};

export const transCategoryNames: { [key: string]: string } = {
  Groceries: "식료품 🛒",
  Rent: "임대료 🏠",
  Salary: "급여 💰",
  Freelancing: "프리랜서 👨🏻‍💻",
  Utilities: "공과금 💡",
  Electronics: "전자제품 🖥️",
  "Dining Out": "외식 🍽️",
  "Breakfast Supplies": "아침 식사 🥐",
  "Household Items": "가정용품 🏡",
  "Christmas Gifts": "크리스마스 선물 🎁",
  "New Year Party Supplies": "새해 파티 🎉",
  "Thanksgiving Groceries": "명절 식료품 🦃",
  Bonus: "보너스 🎊",
  "Consulting Work": "컨설팅 작업 💼",
  "Part-time Job": "알바 ⌚",
  "Online Sales": "온라인 판매 🛒",
  "Freelance Writing": "프리랜서 작문 ✍️",
  "End of Year Bonus": "연말 보너스 🍾",
  Thanksgiving: "명절 용돈 🍂",
  "Thanksgiving Freelance": "명절 용돈 🍂",
  Default: "기본 🫰🏼",
};
